# Generated by Django 4.1.2 on 2022-11-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nome_cientifico', models.CharField(max_length=40)),
                ('classe', models.CharField(max_length=20)),
                ('familia', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caracteristica', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Zoologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=40)),
                ('numero_de_animais', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Zoologicos',
            },
        ),
    ]
